# Generated by Django 2.1.7 on 2019-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_auth', '0002_fix_microsoft_id_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftaccount',
            name='refresh_token',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='microsoftaccount',
            name='token',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='microsoftaccount',
            name='token_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
