#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

pushd "$ROOT_PATH" 2>&1 >/dev/null

echo "Running isort..."
isort .
echo

echo "Running black..."
black .
echo

popd 2>&1 >/dev/null
