#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

pushd "$ROOT_PATH" 2>&1 >/dev/null

dj_versions=("3.2" "4.0" "4.1")
dj_stable="4.1"

for dj_version in "${dj_versions[@]}"; do
    echo "Generating requirements for Django $dj_version..."
    if [[ "$dj_version" == "$dj_stable" ]]; then
        echo -e "django~=$dj_stable\ndjango-constance[database]" > django.in
    else
        echo -e "django~=$dj_stable" > django.in
    fi
    pip-compile --pip-args='--root-user-action=ignore' -q --extra=dev --extra=ql --upgrade --output-file=reqs/dj$dj_version-requirements.txt pyproject.toml django.in
    rm django.in
done

echo "Installing new requirements..."
pip install --root-user-action=ignore -r ./reqs/dj$dj_stable-requirements.txt
pip install --root-user-action=ignore -e ".[dev,ql]"

popd 2>&1 >/dev/null
